# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# SITE SETTINGS
title: GloBAM
description: Monitoring, understanding and forecasting global biomass flows of aerial migrants
author: GloBAM partners

# SOCIAL PROFILES
email: globam@vogelwarte.ch
twitter_username: globam_net
github_username: enram

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish
posts_on_home: 3
tweets_on_home: true
archive_permalink: /news/
logo: /assets/images/globam-nav-logo.png
colors:
  links: "#93c243"
  banner: "#93c243"
  footer: "#513266"

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed                         # Create RSS feed for posts
  - jekyll-sitemap                      # Create sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
