# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-44LHW7Y778"
    anonymize_ip         : # true, false (default)

# SITE SETTINGS
title: CSL@CNU-GSDS
author: CSL

# SOCIAL PROFILES
social:
  email: ihong@jnu.ac.kr
  twitter: 
  github: csl-ds

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
posts_on_home: 2
tweets_on_home: false
archive_permalink: /news/
github_edit: false
logo: 
colors:
  # links: "#93c243"
  # banner: "#93c243"
  # footer: "#513266"
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#007bff"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well wi
font_serif: false

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
